{% set name = "egglib" %}
{% set version = "3.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EggLib-{{ version }}.zip
  sha256: 08fb8b5393e310fdec4bc81efe1d1798f5cfff6cc4f4530ca93c7bd9624d0ad5
  patches:
    - 0001-setup.py.patch  # [osx]

build:
  number: 0
  skip: True  # [py < 38]
  script:
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"
    - export CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include"
    - export CFLAGS="${CFLAGS} -O3 -Wno-implicit-function-declaration"
    - export CPATH="${PREFIX}/include"
    - export LIBRARY_PATH="${PREFIX}/lib"
    - export HTSLIB="${PREFIX}/lib"
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - egglib-config = egglib.cli.config:main
    - egglib-test = egglib.cli.test:main
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - setuptools
    - svgwrite
    - sphinx
    - numpydoc
    - htslib
    - swig
  run:
    - python
    - platformdirs
    - click
    - htslib
    - scipy

test:
  imports:
    - egglib
    - egglib.coalesce
    - egglib.io
    - egglib.stats
    - egglib.tools
    - egglib.wrappers

about:
  home: "https://egglib.org"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Evolutionary Genetics and Genomics Library. EggLib is a C++/Python library and program package for evolutionary genetics and genomics. Main features are sequence data management, sequence polymorphism analysis, and coalescent simulations. EggLib is a flexible Python module with a performant underlying C++ library and allows fast and intuitive development of Python programs and scripts."
  doc_url: "https://www.egglib.org/index.html"
  dev_url: "https://gitlab.com/demita/egglib"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - ranwez
  identifiers:
    - doi:10.1111/1755-0998.13672
    - biotools:egglib
