{% set name = "perl-sys-info-driver-osx" %}
{% set version = "0.7962" %}
{% set sha256 = "617741a437b51ae2a31cc68ad60056a949d3518b6deef740ca0dc6a0d07e24f4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BU/BURAK/Sys-Info-Driver-OSX-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
  weak:
    - {{ name }} ={{ version }}

requirements:
  host:
    - perl
    - perl-extutils-makemaker
    - perl-mac-propertylist
    - perl-test-sys-info
    - perl-sys-info-base
    - perl-capture-tiny
  run:
    - perl
    - perl-parent
    - perl-mac-propertylist
    - perl-capture-tiny
    - perl-sys-info-base

test:
  imports:
    - Sys::Info::Driver::OSX
    - Sys::Info::Driver::OSX::Device
    - Sys::Info::Driver::OSX::Device::CPU
    - Sys::Info::Driver::OSX::OS

about:
  home: http://metacpan.org/pod/Sys::Info::Driver::OSX
  license: perl_5
  summary: 'OSX driver for Sys::Info'

extra:
  recipe-maintainers:
    - xileF1337
  skip-lints:
    - should_be_noarch_generic
